### PR TITLE
Added support for curl options

### PR DESCRIPTION
**Pull request by BigOHenry**
Added support to set curl options.

### CODE REVIEW

**Comment by BigOHenry** [comment]
When i am thinking about it. I can create new `Factory` class from interface `IFactory`, but problem is method `createGuzzleClient()`, there should be input array parameter for curl options (like in PR).

Yeah, curl options should be defined dynamically.

Should i change it in PR or you will do it?

Thank you very much!

**Comment by h4kuna** [comment]
You can change it by `git push --force` but i don't know exactly how resolve it.
Maybe Ares::loadData can have second parametr with options.
Could you show me use case. How you want use it?

**Comment by h4kuna** [comment]
Here is example how i think it d4333cd8159f882591f5d86f3fcaede233767935

**Comment by BigOHenry** [comment]
Yeah, thats fine too :-)

**Comment by h4kuna** [comment]
Fixed in this commit 6e481450863af0614643a7dbcc1cb692057271ff

**Pull request closed without merging**
