### PR TITLE
Added nace to output data

### PR DESCRIPTION
**Pull request by BigOHenry**
More info in #9

### CODE REVIEW

**Comment by h4kuna** [comment]
Look like good, could you create test.

**Comment by BigOHenry** [comment]
Sorry, but i dont know why test failed: `ERROR: An error occured while trying to fetch your .travis.yml file.`
I added nace data into both json`s.

**Comment by h4kuna** [comment]
Thank you, released new [version 1.4.3](/h4kuna/ares/releases/tag/v1.4.3)

**Comment by BigOHenry** [comment]
Thank you man!

**Pull request closed without merging**
